# Generated by Django 5.0.7 on 2024-07-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_item',
            field=models.ManyToManyField(related_name='item', to='core.item'),
        ),
    ]
